apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-session-cluster
spec:
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: query
    port: 6125
  - name: ui
    port: 8081
    nodePort: 30081
  type: LoadBalancer
  selector:
    app: flink
    component: jobmanager
